# Generated by Django 4.2.1 on 2023-05-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_categorias_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.categoria'),
        ),
    ]
