# Generated by Django 4.2.1 on 2023-05-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoriaProducto',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='description',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='name',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='detalleProducto',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='existenciaProducto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaCreacionProducto',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaModificacionProducto',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioCompraProducto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioVentaProducto',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacionOrdenCompra', models.DateTimeField(null=True)),
                ('estadoOrdenCompra', models.BooleanField(null=True)),
                ('productoOrdenCompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoHistorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.producto')),
            ],
        ),
    ]
