# Generated by Django 4.2.1 on 2023-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_subcategoria_alter_producto_categoriaproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='subcategoria',
            new_name='categoriaAsociada',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='nombreSubcategoria',
            new_name='nombreSubCategoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagenCategoria',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='imagenSubcategoria',
            field=models.ImageField(blank=True, null=True, upload_to='subcategorias/'),
        ),
    ]
