# Generated by Django 4.2.1 on 2023-06-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_subcategoria_subcategoria_categoriaasociada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoriaProducto',
            new_name='subCategoriaProducto',
        ),
    ]
