# Generated by Django 4.2.1 on 2023-06-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_categoriaproducto_producto_subcategoriaproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='detalleProducto',
            new_name='descripcionCortaProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcionDetalladaProducto',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProductoCuatro',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProductoDos',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProductoTres',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='medidasProducto',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
